# Generated by Django 4.1.4 on 2022-12-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='name',
            new_name='title',
        ),
    ]
