# Generated by Django 4.1.4 on 2023-01-11 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_password_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
